version: "3.8"
services:
  telegram:
    build:
        context: ./telegram
        dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
  discord:
    build:
        context: ./discord
        dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
